server:
  port: 8080
  servlet:
    context-path: /xuanbac

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://mysql:3306/crm_service}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true